### ISSUE TITLE
clang 3.6 gives "Undefined bool conversion" in ClonePtr

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#388]
```
/Users/chris/repos/simbody/1/install/include/simbody/SimTKcommon/internal/ClonePtr.h:84:16
: warning: 
      reference cannot be bound to dereferenced null pointer in well-defined C++
      code; pointer may be assumed to always convert to true
      [-Wundefined-bool-conversion]
    {   reset(&t ? t.clone()  :0); return *this; }
```

http://stackoverflow.com/questions/28689269/how-to-fix-reference-cannot-be-bound-to-dereferenced-null-pointer-warning

Any ideas on how to fix this?

**Comment by sherm1** [comment]
> Any ideas on how to fix this?

Yes. The code is trying to protect itself from the supplied `const T& t` being a reference to null, which in theory "can't happen" (actually it can but only by illegal code like `const T& t = *reinterpret_cast<T*>(nullptr)`). The compiler is saying that it is free to assume therefore that `&t` always returns non-null, so that the `t.clone()` branch of the `?:` will be executed unconditionally. So the fix is to stop checking for the "impossible" null case. Change the above line to 
```
{   reset(t.clone()); return *this; }
```
If someone actually passes a null reference then the caller has a bug. If they actually have a null pointer, they should have used one of the overloads that takes a pointer rather than a reference.

P.S. There is at least one more instances of this [a few lines earlier](https://github.com/simbody/simbody/blob/master/SimTKcommon/include/SimTKcommon/internal/ClonePtr.h#L68); not sure why you didn't see a warning there too.
