### ISSUE TITLE
Remove support for long double

### ISSUE THREAD

**Issue by antoinefalisse** [simbody/simbody#596]
@sherm1, @chrisdembia, as previously discussed, I will work on a PR to remove support for` long double`.

I scanned through all files of Simbody looking for `long double`. I listed 15 files using `long double` (+ 5 files mentioning `long double` in comments only) in SimTKcommon as well as 6 tests. I did not find any `long double` in `SimTKmath` and `SimTKsimbody`.

I am wondering how I should deal with files such as `Constants.h` where the constants are defined using `long double` precision: eg `#define SimTK_PI     3. ... L`. Note that there could be other files where this `L` is used. 

Would it be too big to include all changes in a singlePR?

**Comment by sherm1** [comment]
> Would it be too big to include all changes in a singlePR?

I think it will be fine since it is a single concept and should be easy to review. It isn't just the number of changes that makes a PR hard to review -- it is much more difficult to review a PR that tries to address several independent goals at the same time.

Regarding the constants that use L, please leave those as is -- that just indicates they are at the highest available precision. When put into a float or a double they get rounded to the right precision.
