### ISSUE TITLE
Expose `SimbodyMatterSubsystemRep::multiplyByPVATranspose` to `SimbodyMatterSubsystem`

### ISSUE THREAD

**Issue by nickbianco** [simbody/simbody#782]
I am currently working a new method for enforcing kinematic constraints in OpenSim Moco (opensim-org/opensim-core#3587). This method relies requires a projection of the coordinate states in a manner analoguous to Simbody's approach where a vector is multiplied by components of the kinematic constraint Jacobian `G = [P; V; A]`. 

Like Simbody (or as far as I understand what Simbody is doing), I project the coordinate values and coordinate speeds separately. I use the `SimbodyMatterSubsystem::multiplyByPqTranspose` for the `q` projections, but there is currently no similar method available for projecting only the coordinate speeds. `SimbodyMatterSubsystem::multiplyByGTranspose` is available, but includes slots for acceleration constraints, which I don't need.

I recently found `SimbodyMatterSubsystemRep::multiplyByPVATranspose`, which seems perfect for this (I can configure it to give me a `[P; V]` transpose multiplication), but it is not available in `SimbodyMatterSubsystem`.

@sherm1 what do you think about exposing this functionality? Seems pretty straightforward at first glance. I can start working on this locally and, if it makes sense, open a PR soon.

**Comment by sherm1** [comment]
Than, Nick! I think I didn't expose the general PVA function because of its awkward interface and complicated description -- instead I used it to implement simpler APIs. I wouldn't object to exposing it, but it might be cleaner just to add a function `multibodyByPVTranspose()` to the public API since we now know that's useful! Then you would only have to document that in the same manner as `multibodyByGTranpose()` with the implementation similar but (true,true,false) rather than all true. There should be a unit test or two to make sure it doesn't get broken in the future -- that would also be easier with a PV API than the general one.

I would welcome a PR adding this nice functionality!
